services:
  elastic:
    image: elasticsearch:8.14.3
    container_name: elastic
    hostname: elastic
    user: "elasticsearch"
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx10G"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9200:9200
    networks:
      - pydoptic-test

  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=pydoptic
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pydoptic-test

networks:
  pydoptic-test:
